# Form implementation generated from reading ui file './QT_file/ManualWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManualWindow(object):
    def setupUi(self, ManualWindow):
        ManualWindow.setObjectName("ManualWindow")
        ManualWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ManualWindow.resize(502, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/statics/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ManualWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ManualWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(parent=ManualWindow)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(parent=ManualWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setSource(QtCore.QUrl("qrc:/manual.md"))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(ManualWindow)
        QtCore.QMetaObject.connectSlotsByName(ManualWindow)

    def retranslateUi(self, ManualWindow):
        _translate = QtCore.QCoreApplication.translate
        ManualWindow.setWindowTitle(_translate("ManualWindow", "使用說明"))
        self.exit_btn.setText(_translate("ManualWindow", "離開"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualWindow = QtWidgets.QWidget()
    ui = Ui_ManualWindow()
    ui.setupUi(ManualWindow)
    ManualWindow.show()
    sys.exit(app.exec())
